# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pbssim <- function(responses, predictors, initial_alpha, degree, number_interior_knots, number_lambdas_alpha, number_lambdas_beta, lambda_alpha_max = 100, lambda_beta_max = 10, epsilon_lambda = 1e-6, maxiter = 200L, epsilon_iterations = 1e-4) {
    .Call('_pbssim_pbssim', PACKAGE = 'pbssim', responses, predictors, initial_alpha, degree, number_interior_knots, number_lambdas_alpha, number_lambdas_beta, lambda_alpha_max, lambda_beta_max, epsilon_lambda, maxiter, epsilon_iterations)
}

bsplines <- function(x, t, degree = 1L, derivative = 0L) {
    .Call('_pbssim_bsplines', PACKAGE = 'pbssim', x, t, degree, derivative)
}

bspline <- function(x, t, degree = 1L, j = 0L, derivative = 0L) {
    .Call('_pbssim_bspline', PACKAGE = 'pbssim', x, t, degree, j, derivative)
}

bsp <- function(x, t, degree, j) {
    .Call('_pbssim_bsp', PACKAGE = 'pbssim', x, t, degree, j)
}

dbsp <- function(x, t, degree, j, derivative) {
    .Call('_pbssim_dbsp', PACKAGE = 'pbssim', x, t, degree, j, derivative)
}

jump_bsplines <- function(t, degree = 1L) {
    .Call('_pbssim_jump_bsplines', PACKAGE = 'pbssim', t, degree)
}

knots2t <- function(knots, degree = 1L) {
    .Call('_pbssim_knots2t', PACKAGE = 'pbssim', knots, degree)
}

dim2knots <- function(predictor, dimension, degree) {
    .Call('_pbssim_dim2knots', PACKAGE = 'pbssim', predictor, dimension, degree)
}

NumericVectors <- function(size) {
    .Call('_pbssim_NumericVectors', PACKAGE = 'pbssim', size)
}

IntegerVectors <- function(size) {
    .Call('_pbssim_IntegerVectors', PACKAGE = 'pbssim', size)
}

support_of_vector <- function(v) {
    .Call('_pbssim_support_of_vector', PACKAGE = 'pbssim', v)
}

bubble_order <- function(vec) {
    .Call('_pbssim_bubble_order', PACKAGE = 'pbssim', vec)
}

subsetNumVec <- function(x, index) {
    .Call('_pbssim_subsetNumVec', PACKAGE = 'pbssim', x, index)
}

subsetIntVec <- function(x, index) {
    .Call('_pbssim_subsetIntVec', PACKAGE = 'pbssim', x, index)
}

knot_candidate <- function(predictors, knot_size) {
    .Call('_pbssim_knot_candidate', PACKAGE = 'pbssim', predictors, knot_size)
}

norm_2 <- function(u) {
    .Call('_pbssim_norm_2', PACKAGE = 'pbssim', u)
}

norm_square <- function(u) {
    .Call('_pbssim_norm_square', PACKAGE = 'pbssim', u)
}

zlambda <- function(a, b, c, d, lambda) {
    .Call('_pbssim_zlambda', PACKAGE = 'pbssim', a, b, c, d, lambda)
}

delta <- function(d) {
    .Call('_pbssim_delta', PACKAGE = 'pbssim', d)
}

q_lambda_point <- function(z, a, b, c, d, lambda) {
    .Call('_pbssim_q_lambda_point', PACKAGE = 'pbssim', z, a, b, c, d, lambda)
}

lambdas_all_alpha <- function(number_lambdas_alpha, lambda_alpha_max, epsilon_lambda) {
    .Call('_pbssim_lambdas_all_alpha', PACKAGE = 'pbssim', number_lambdas_alpha, lambda_alpha_max, epsilon_lambda)
}

lambdas_all_beta <- function(number_lambdas, lambda_beta_max, epsilon_lambda) {
    .Call('_pbssim_lambdas_all_beta', PACKAGE = 'pbssim', number_lambdas, lambda_beta_max, epsilon_lambda)
}

alpha2xi <- function(alpha) {
    .Call('_pbssim_alpha2xi', PACKAGE = 'pbssim', alpha)
}

xi2alpha <- function(xi) {
    .Call('_pbssim_xi2alpha', PACKAGE = 'pbssim', xi)
}

deriv_xi_j <- function(xi, alpha, j) {
    .Call('_pbssim_deriv_xi_j', PACKAGE = 'pbssim', xi, alpha, j)
}

atan4 <- function(y, x) {
    .Call('_pbssim_atan4', PACKAGE = 'pbssim', y, x)
}

